springdoc:
  api-docs:
    enabled: true
    path: /docs/api-docs
  swagger-ui:
    path: /docs/swagger.html

spring:
  lifecycle:
    timeout-per-shutdown-phase: "10s"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Sao_Paulo
  jpa:
    open-in-view: false
  datasource:
    hikari:
      maxLifetime: '2000000'
      poolName: SpringBootHikariCP
      connectionTimeout: '30000'
      idleTimeout: '30000'
      minimumIdle: '5'
      maximumPoolSize: '20'
      schema: public
    url: jdbc:postgresql://158.69.122.78:5432/postgres
    type: com.zaxxer.hikari.HikariDataSource
    username: postgres
    password: certivale

server:
  port: 8091
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
application:
  formatted-version: v1.0
  title: DanceHub-API
