springdoc:
  api-docs:
    enabled: true
    path: /docs/api-docs
  swagger-ui:
    path: /docs/swagger.html

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "XXXXXXXXXXXXXXXXXXXXXXXXX"
    password: "XXXXXXXXXXXXXXXXXXXXXXXXX"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: "10s"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Sao_Paulo
  jpa:
    open-in-view: false
  datasource:
    hikari:
      maxLifetime: '2000000'
      poolName: SpringBootHikariCP
      connectionTimeout: '30000'
      idleTimeout: '30000'
      minimumIdle: '5'
      maximumPoolSize: '20'
      schema: public
    url: XXXXXXXXXXXXXXXXXXXXXXXXX
    type: com.zaxxer.hikari.HikariDataSource
    username: XXXXXXXXXXXXXXXXXXXXXXXXX
    password: XXXXXXXXXXXXXXXXXXXXXXXXX

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  port: 8091
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
application:
  formatted-version: v1.0
  title: DanceHub-API
